apiVersion: v1
kind: ConfigMap

metadata:
  name: live
  namespace: tws

data:
  IBC_TRADING_MODE: "live"
  IBC_STORE_SETTINGS_ON_SERVER: "yes"
  IBC_READONLY_LOGIN: "yes"
  VNC_DISPLAY: "0"
  TZ: "Europe/London"

---

apiVersion: v1
kind: ConfigMap

metadata:
  name: paper
  namespace: tws

data:
  IBC_TRADING_MODE: "paper"
  IBC_STORE_SETTINGS_ON_SERVER: "no"
  IBC_READONLY_LOGIN: "yes"
  VNC_DISPLAY: "1"
  TWS_API_PORT: "7497"
  TZ: "Europe/London"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tws
  namespace: tws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tws
      trading-mode: combined
  template:
    metadata:
      labels:
        app: tws
        trading-mode: combined
    spec:
      volumes:
        - name: conf
          secret:
            secretName: ibkr-conf
        - name: home
          emptyDir:
        - name: jts-live
          emptyDir:
        - name: jts-paper
          emptyDir:
      containers:
        - name: live
          image: registry.mycorp.mydomain/tws
          volumeMounts:
          - mountPath: /home/tws
            name: home
          - mountPath: /home/tws/Jts
            name: jts-live
          - mountPath: /conf
            name: conf

          envFrom:
          - secretRef:
              name: ibkr-creds
          - configMapRef:
              name: live
          ports:
          - name: vnc
            containerPort: 5900
          - name: ibc
            containerPort: 7462
          - name: live
            containerPort: 7496

        - name: paper
          image: registry.mycorp.mydomain/tws
          volumeMounts:
          - mountPath: /home/tws
            name: home
          - mountPath: /home/tws/Jts
            name: jts-paper
          - mountPath: /conf
            name: conf

          envFrom:
          - secretRef:
              name: ibkr-creds
          - configMapRef:
              name: paper
          ports:
          - name: vnc
            containerPort: 5901
          - name: ibc
            containerPort: 7463
          - name: paper
            containerPort: 7497

---

kind: Service
apiVersion: v1
metadata:
  name: live
  namespace: tws
  labels:
    app: tws
    trading-mode: live
spec:
  selector:
    app: tws
    trading-mode: combined
  ports:
  - name: vnc
    port: 5900
    targetPort: 5900
  - name: ibc
    port: 7462
    targetPort: 7462
  - name: live
    port: 7496
    targetPort: 7496

---

kind: Service
apiVersion: v1
metadata:
  name: paper
  namespace: tws
  labels:
    app: tws
    trading-mode: paper
spec:
  selector:
    app: tws
    trading-mode: combined
  ports:
  - name: vnc
    port: 5900
    targetPort: 5901
  - name: ibc
    port: 7462
    targetPort: 7463
  - name: paper
    port: 7497
    targetPort: 7497
